server:
  port: 8082
spring:
  application:
    name: yuan-test
  datasource:
    url: jdbc:mysql://localhost:3306/yuan_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 172.23.80.90:8848
  data:
    redis:
      host: 172.23.80.90
      port: 6379
      password: Lqy147258369
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jmeter:
  home: D:/AForAll/AutoTest/Jmeter/apache-jmeter-5.6.3
  results-dir: E:/AI/workspace/projects/yuan/jmeter/results/
  scripts-dir: E:/AI/workspace/projects/yuan/jmeter/scripts/
