server:
  port: 8085
spring:
  application:
    name: yuan-report
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:Lqy147258369}
  thymeleaf:
    cache: true

