server:
  port: 8082
spring:
  application:
    name: yuan-test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/yuan_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:Lqy147258369}
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:producer}
    password: ${RABBITMQ_PASSWORD:123456}
    virtual-host: ${RABBITMQ_VHOST:test_monitor}
jmeter:
  home: ${JMETER_HOME:D:/apache-jmeter-5.6.3}
  results-dir: ${JMETER_RESULTS_DIR:E:/AI/workspace/projects/yuan/jmeter/results/}
  scripts-dir: ${JMETER_SCRIPTS_DIR:E:/AI/workspace/projects/yuan/jmeter/scripts/}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

